[project]
title = "SPHEREx Sphinx"
copyright = "2022 California Institute of Technology"
base_url = "https://spherex-docs.ipac.caltech.edu/spherex-sphinx/"
github_url = "https://github.com/SPHEREx/spherex-sphinx"

[sphinx.intersphinx.projects]
python = "https://docs.python.org/3"
sphinx = "https://www.sphinx-doc.org/en/master/"
