name: Python CI

"on":
  push: {}
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Run tox
        uses: lsst-sqre/run-tox@v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "py,typing"

  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Run tox
        uses: lsst-sqre/run-tox@v1
        with:
          python-version: "3.12"
          tox-envs: "demo"

      - name: Upload MD technote demo artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdown-technote
          path: demo/md-technote/_build/html

      - name: Upload rst technote demo artifact
        uses: actions/upload-artifact@v4
        with:
          name: rst-technote
          path: demo/rst-technote/_build/html

      - name: Upload ipynb technote demo artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipynb-technote
          path: demo/ipynb-technote/_build/html

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for setuptools_scm

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Run tox
        uses: lsst-sqre/run-tox@v1
        with:
          python-version: "3.12"
          tox-envs: "docs"

      - name: Install LTD Conveyor
        run: pip install "ltd-conveyor==0.9.0a2"

      - name: Upload documentation
        if: github.event_name == 'push'
        env:
          LTD_PASSWORD: ${{ secrets.docs_api_password }}
          LTD_USERNAME: spherex-upload
        run: |
          ltd --host https://docs-api.ipac.caltech.edu upload --org spherex --project spherex-sphinx --gh --dir docs/_build/html
